DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Areas/Administrator/Controllers/OpenRequestController.cs
using MySql.Data.MySqlClient;
using OnlineRequestSystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineRequestSystem.Areas.Administrator.Models;

namespace OnlineRequestSystem.Areas.Administrator.Controllers
{
    public class OpenRequestController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(OpenRequestController));
        // GET: Administrator/OpenRequest
        public ActionResult OpenRequest()
        {
            if (Convert.ToInt32(Session["Utility"]) == 1)
            {
                return View();
            }
            else
            {
                return View("_Unauthorized");
            }

        }
        public JsonResult SearchReqNumber(string reqno, string zone)
        {
            try
            {
                if (reqno == string.Empty || zone == string.Empty)
                    return Json(new { status = true, rescode = "0", msg = "No data found", }, JsonRequestBehavior.AllowGet);

                ORtoMySql db = new ORtoMySql();
                List<RequestModels> list = new List<RequestModels>();
                using (MySqlConnection conn = db.getConnection())
                {
                    conn.Open();
                    using (MySqlCommand cmd = conn.CreateCommand())
                    {
                        string Query = "SELECT * FROM onlinerequest_open WHERE reqnumber = @reqno and ZoneCode = @zone";
                        cmd.Parameters.AddWithValue("@reqno", reqno);
                        cmd.Parameters.AddWithValue("@zone", zone);
                        cmd.CommandText = Query;
                        using (MySqlDataReader read = cmd.ExecuteReader(CommandBehavior.CloseConnection))
                        {
                            if (read.HasRows)
                            {
                                while (read.Read())
                                {
                                    RequestModels x = new RequestModels();
                                    x.id = Convert.ToInt32(read["id"].ToString().Trim());
                                    x.reqNumber = read["reqNumber"].ToString().Trim();
                                    x.reqDate = read["reqDate"].ToString().Trim();
                                    x.reqCreator = read["reqCreator"].ToString().Trim();
                                    x.TypeID = read["TypeID"].ToString().Trim();
                                    x.BranchCode = read["BranchCode"].ToString().Trim();
                                    x.Region = read["Region"].ToString().Trim();
                                    x.Area = read["Area"].ToString().Trim();
                                    x.AreaCode = read["AreaCode"].ToString().Trim();
                                    x.DivCode = read["DivCode"].ToString().Trim();
                                    x.ZoneCode = read["ZoneCode"].ToString().Trim();
                                    x.Status = read["reqStatus"].ToString().Trim();
                                    x.SysCreated = read["syscreated"].ToString().Trim();
                                    x.SysCreator = read["syscreator"].ToString().Trim();
                                    x.ForPresident = read["forPresident"].ToString().Trim();
                                    list.Add(x);
                                }

                                return Json(new
                                {
                                    status = true,
                                    data = list,
                                    rescode = "200",
                                }, JsonRequestBehavior.AllowGet);
                            }
                            else
                            {
                                return Json(new
                                {
                                    status = false,
                                    rescode = "400",
                                    msg = "No data found",
                                }, JsonRequestBehavior.AllowGet);
                            }
                        }
                    }
                }
            }
            catch (Exception x)
            {
                log.Fatal(x.Message, x);
                return Json(new
                {
                    status = false,
                    rescode = "500",
                    msg = "Error",
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult OpenExecuteQue(string query)
        {
            try
            {
                ORtoMySql db = new ORtoMySql();
                object divecodeResult = "";
                using (MySqlConnection con = db.getConnection())
                {
                    con.Open();
                    MySqlCommand cmd = con.CreateCommand();
                    cmd.CommandText = query;
                    var result = cmd.ExecuteNonQuery();
                }
                return Json(new
                {
                    status = true,
                    rescode = "200",
                    msg = "Success",
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception x)
            {
                log.Fatal(x.Message, x);
                return Json(new
                {
                    status = false,
                    rescode = "500",
                    msg = "Error",
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Controllers/MMDController.cs
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
using OnlineRequestSystem.Dataset;
using OnlineRequestSystem.Models;
using OnlineRequestSystem.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace OnlineRequestSystem.Controllers
{
    public class MMDController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(MMDController));
        private DateTime syscreated = DateTime.Now;
        private DateTime sysmodified = DateTime.Now;
        private OpenRequestController open = new OpenRequestController();
        private MMDQueries que = new MMDQueries();
        private Helper set = new Helper();
        private string format = "yyyy/MM/dd HH:mm:ss";

        public ActionResult Index()
        {
            return View();
        }

        #region Display MMD Status

        public ActionResult viewMMDStatus(string selected, string type, string retUrl, string office)
        {
            var mySession = (ORSession)Session["UserSession"];
            if (mySession == null) return RedirectToAction("Logout", "Userlogin");

            try
            {
                var Info = new OpenReqInfo();
                var toTC = new CultureInfo("en-US", false).TextInfo;
                var db = new ORtoMySql();
                using (var conn = db.getConnection())
                {
                    var OpenReqList = new List<OpenReqViewModel>();
                    var cmd = conn.CreateCommand();

                    conn.Open();
                    if (type == "PO")
                    {
                        if ((new[] { "VISMIN", "VISAYAS", "MINDANAO" }).Contains(mySession.s_zonecode))
                        {
                            switch (selected)
                            {
                                case "PROCESSED PO":

                                    #region PP Query

                                    cmd.CommandText = "SELECT a.reqNumber, a.reqCreator, COUNT(d.itemDescription) AS TotalCount, a.reqDescription, a.OverallTotalPrice, a.reqDate, a.TypeID , " +
                                  " (SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                  " a.reqTotal, a.BranchCode, a.Region, a.DivCode,  a.Zonecode, a.reqStatus, a.TotalQty, a.isDivRequest, a.DeptCode, " +
                                  " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, b.isRMReceived, b.isRMTransit FROM onlineRequest_Open a   " +
                                  " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber  " +
                                  " INNER JOIN requestType c  ON a.TypeID = c.TypeID  " +
                                  " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber " +
                                  " WHERE a.isDivRequest = @office AND b.isMMDProcessed = 1 AND b.isMMDTransit = 0 " +
                                  " AND b.isPO_Approved = 1 " +
                                  " AND b.isDelivered = 0 AND (a.ZoneCode = 'VISMIN' OR a.ZoneCode = 'VISAYAS' OR a.ZoneCode = 'MINDANAO') " +
                                  " GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";

                                    #endregion PP Query

                                    break;

                                case "RECEIVED FROM SUPPLIER":

                                    #region RFS Query

                                    cmd.CommandText = "SELECT  a.reqNumber,  a.reqCreator, COUNT(d.itemDescription) AS TotalCount, a.reqDescription, a.OverallTotalPrice, a.reqDate, a.TypeID , " +
                                  " (SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                  " a.reqTotal, a.BranchCode, a.Region, a.DivCode,  a.Zonecode, a.reqStatus, a.TotalQty, a.isDivRequest, a.DeptCode, " +
                                  " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, b.isRMReceived, b.isRMTransit FROM onlineRequest_Open a   " +
                                  " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber " +
                                  " INNER JOIN requestType c  ON a.TypeID = c.TypeID " +
                                  " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber " +
                                  " WHERE  a.isDivRequest = @office AND b.isDelivered = 0 AND b.isMMDTransit = 1 " +
                                  " AND b.isPO_Approved = 1 " +
                                  " AND b.isMMDProcessed = 1 AND (a.ZoneCode = 'VISMIN' OR a.ZoneCode = 'VISAYAS' OR a.ZoneCode = 'MINDANAO') " +
                                  " GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";

                                    #endregion RFS Query

                                    break;

                                case "IN TRANSIT-SDC":

                                    #region ITS Query

                                    cmd.CommandText = "SELECT  a.reqNumber,  a.reqCreator, COUNT(d.itemDescription) AS TotalCount, a.reqDescription, a.OverallTotalPrice, a.reqDate, a.TypeID , " +
                                  " (SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                  " a.reqTotal, a.BranchCode, a.Region, a.DivCode,  a.Zonecode, a.reqStatus, a.TotalQty, a.isDivRequest, a.DeptCode, " +
                                  " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, b.isRMReceived, b.isRMTransit FROM onlineRequest_Open a   " +
                                  " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber  " +
                                  " INNER JOIN requestType c  ON a.TypeID = c.TypeID " +
                                  " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber " +
                                  " WHERE a.isDivRequest = @office AND b.isMMDTransit = 1 AND b.isMMDProcessed = 1 " +
                                  " AND b.isPO_Approved = 1 " +
                                  " AND b.isDelivered = 1 AND (a.ZoneCode = 'VISMIN' OR a.ZoneCode = 'VISAYAS' OR a.ZoneCode = 'MINDANAO') " +
                                  " GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";

                                    #endregion ITS Query

                                    break;

                                default:
                                    break;
                            }
                        }
                        else
                        {
                            switch (selected) // LUZON
                            {
                                case "PROCESSED PO":

                                    #region PP Query

                                    cmd.CommandText = "SELECT a.reqNumber,  a.reqCreator, COUNT(d.itemDescription) AS TotalCount,  a.reqDescription, a.OverallTotalPrice, a.reqDate, a.TypeID , " +
                                  " (SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                  " a.reqTotal, a.BranchCode, a.Region, a.DivCode,  a.Zonecode, a.reqStatus, a.TotalQty, a.isDivRequest, a.DeptCode, " +
                                  " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, b.isRMReceived, b.isRMTransit FROM onlineRequest_Open a   " +
                                  " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber  " +
                                  " INNER JOIN requestType c  ON a.TypeID = c.TypeID " +
                                  " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber " +
                                  " WHERE a.isDivRequest = @office AND b.isMMDProcessed = 1 AND b.isMMDTransit = 0 " +
                                  " AND b.isPO_Approved = 1 " +
                                  " AND b.isDelivered = 0 AND (a.ZoneCode = 'LUZON' OR a.ZoneCode = 'LNCR' OR a.ZoneCode = 'NCR') " +
                                  " GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";

                                    #endregion PP Query

                                    break;

                                case "RECEIVED FROM SUPPLIER":

                                    #region RFS Query

                                    cmd.CommandText = "SELECT  a.reqNumber,  a.reqCreator, COUNT(d.itemDescription) AS TotalCount, a.reqDescription, a.OverallTotalPrice, a.reqDate, a.TypeID , " +
                                  " (SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                  " a.reqTotal, a.BranchCode, a.Region, a.DivCode,  a.Zonecode, a.reqStatus, a.TotalQty, a.isDivRequest, a.DeptCode, " +
                                  " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, b.isRMReceived, b.isRMTransit FROM onlineRequest_Open a   " +
                                  " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber  " +
                                  " INNER JOIN requestType c  ON a.TypeID = c.TypeID " +
                                  " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber " +
                                  " WHERE a.isDivRequest = @office AND b.isDelivered = 0 AND b.isMMDTransit = 1 " +
                                  " AND b.isPO_Approved = 1 " +
                                  " AND b.isMMDProcessed = 1 AND (a.ZoneCode = 'LUZON' OR a.ZoneCode = 'LNCR' OR a.ZoneCode = 'NCR') " +
                                  " GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Views/OpenRequest/Div_OpenRequest.cshtml
@model OnlineRequestSystem.Models.OpenReqInfo
@{
    ViewBag.Title = "ViewOpenRequest";
    var mySession = (OnlineRequestSystem.Models.ORSession)Session["UserSession"];

}
<br />

<div id="openBody" class="jumbotron boxShadow col-md-12" style="width:1300px;margin-left:-4.5%; padding-left:0px; padding-right:0px">
    <div class="panel-heading ORSHeading">
        <b class="orHeader">@ViewBag.headTxt</b>
    </div>

    <div style="padding-top:7px;"></div>

    <table class="table-hover" id="DivisionOpenReq">
        <thead>
            <tr>
                <th class="checkAll"><center><input type="checkbox" class="checkAll thChkbox"></center></th>
                <th><center>Select</center></th>
                <th class="col-sm-1"><center>Date Created</center></th>
                <th class="col-sm-2"><center>Request no.</center></th>
                <th class="col-sm-2"><center>Types</center></th>
                <th style="width:6%"><center>Count</center></th>
                <th class="col-sm-1"><center>Description</center></th>
                <th class="col-sm-2"><center>Branch/Division</center></th>
                <th class="col-sm-2"><center>Author</center></th>
                <th class="col-sm-2"><center>Region</center></th>
            </tr>
        </thead>
        <tbody style="font-size:12px;">
            @if (Model._OpenInfo != null)
            {
                foreach (var item in Model._OpenInfo)
                {
                    var dt = Convert.ToDateTime(item.reqDate);
                    var day = (dt.Day < 10) ? "0" + dt.Day.ToString() : dt.Day.ToString();
                    var month = (dt.Month < 10) ? "0" + dt.Month.ToString() : dt.Month.ToString();
                    var year = dt.Year.ToString();

                    var spanReqDate = year + month + day;

                    <tr class="cellspacer">
                        @if (item.reqCreator == mySession.s_fullname)
                        {
                            <td><center><span class="glyphicon glyphicon-user red"></span></center></td>
                        }
                        else
                        {
                            <td><center><input type="checkbox" class="chkBox" /></center></td>
                        }
                        <td><center><button class="btn btn-sm btn-danger" onclick="location.href='@Url.Action("RequestDetails", "OpenRequest", new { ReqNo = item.reqNumber, BranchCode = item.BranchCode, ZoneCode = @item.ZoneCode, Region = @item.Region, retUrl = Model.returnUrl })'">Show Details</button></center></td>
                        <td style="text-align:center" data-sort='@item.sortreqDate'>@item.reqDate</td>
                        <td><center>@item.reqNumber</center></td>
                        <td><center>@item.TypeName</center></td>
                        <td><center>@item.TotalItems</center></td>
                        <td><center>@item.itemDescription</center></td>
                        <td><center>@item.BranchName</center></td>
                        <td><center>@item.reqCreator</center></td>
                        <td>
                            <center>
                                @item.Region
                                <span style="display:none;">@item.BranchCode</span>
                            </center>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <input id="approver" type="text" value="Div" hidden />
    <input id="forFilter" type="text" value="General_usr" hidden />

    &nbsp;&nbsp;&nbsp;
    <button class="btn btn-sm btn-success orHeader" id="DivApprover_mApprove"><i class="fa fa-check"></i> &nbsp;Approve</button>
    <button class="btn btn-sm btn-danger orHeader" id="btnMultiDisapprove"><i class="fa fa-times"></i> &nbsp;Disapprove</button>
</div>

@section tableCss{
    <link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/datetime/1.2.0/css/dataTables.dateTime.min.css" rel="stylesheet" />
}

@section scripts{
    <script type="text/javascript" src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/datetime/1.3.0/js/dataTables.dateTime.min.js"></script>

    @Scripts.Render("~/bundles/openrequestlibraries")

    @Scripts.Render("~/bundles/openrequests")
    <script>
        $('.chkBox').each(function () {
            this.checked = false;
        });
        var clssCount = $('.chkBox').length;
        $(document).ready(function () {
            $(".checkAll").click(function () {
                $('.chkBox:checkbox').not(this).prop('checked', this.checked);
            });
        });
    </script>
}

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Views/OpenRequest/ViewOpenRequest.cshtml
@model OnlineRequestSystem.Models.OpenReqInfo
@{
    ViewBag.Title = "ViewOpenRequest";
    var mySession = (OnlineRequestSystem.Models.ORSession)Session["UserSession"];

    var ORHeading = string.Empty;

    if (Model.POurl == "PO")
    {
        ORHeading = "ORSHeadingPO";
    }
    else
    {
        ORHeading = "ORSHeading";
    }
}
<br />

<div id="openBody" class="jumbotron boxShadow col-md-12" style="width:1300px;margin-left:-4.5%; padding-left:0px; padding-right:0px">
    <div class="panel-heading @ORHeading">
        <b class="orHeader">@ViewBag.headTxt REQUESTS</b>
        @if ((new[] { "0001MMD", "0002MMD", }).Contains(mySession.s_costcenter))
        {
            <div class="pull-right" style="color:black;">
                <button class="mmdLoad" onclick="location.href='@Url.Action("viewMMDStatus", "MMD", new { selected = "PROCESSED PO", retUrl = Model.returnUrl, office = Model.office })'"><i> Processed PO </i></button>
                <button class="mmdLoad" onclick="location.href='@Url.Action("viewMMDStatus", "MMD", new { selected = "RECEIVED FROM SUPPLIER", retUrl = Model.returnUrl, office = Model.office })'"><i> Received from supplier </i></button>
                <button class="mmdLoad" onclick="location.href='@Url.Action("viewMMDStatus", "MMD", new { selected = "IN TRANSIT-SDC", retUrl = Model.returnUrl, office = Model.office })'"><i> In-Transit </i></button>
            </div>
        }
    </div>
    @if (mySession.s_isDepartmentApprover == 1)
    {
        @Html.Partial("OpenReqPartials/_DepartmentManager", Model);
    }
    else if (mySession.s_job_title == "AREA MANAGER")
    {
        @Html.Partial("OpenReqPartials/_AreaManager", Model);
    }
    else if (mySession.s_job_title == "REGIONAL MAN")
    {
        @Html.Partial("OpenReqPartials/_RegionalManager", Model);
    }
    else if (mySession.s_usr_id == "LHUI1011873")
    {
        @Html.Partial("OpenReqPartials/_President", Model);
    }
    else
    {
        if (mySession.s_isDepartmentApprover != 1)
        {
            <div style="padding-top:7px;"></div>
            <table class="table-hover" id="BMorOthers">
                <thead>
                    <tr>
                        <th style="text-align:center">Select</th>
                        <th class="col-sm-1" style="text-align:center">Date Created</th>
                        <th class="col-sm-2" style="text-align:center">Request no.</th>
                        <th class="col-sm-2" style="text-align:center">Type</th>
                        <th class="col-sm-1" style="text-align:center">Count</th>
                        <th class="col-sm-2" style="text-align:center">Description</th>
                        <th class="col-sm-2" style="text-align:center">Branch/Division</th>
                        <th class="col-sm-2" style="text-align:center">Author</th>
                        <th class="col-sm-2" style="text-align:center">Region</th>
                    </tr>
                </thead>
                <tbody style="font-size:12px;" id="tbodys">
                    @if (Model._OpenInfo != null)
                    {
                        foreach (var item in Model._OpenInfo)
                        {
                            if (item.reqCreator == mySession.s_fullname && item.reqStatus == "OPEN")
                            {
                                <tr class="cellspacer" style="cursor:pointer;">
                                    <td style="text-align:center"><button class="btn btn-sm btn-danger" onclick="location.href = '@Url.Action("RequestDetails", "OpenRequest", new { ReqNo = item.reqNumber , BranchCode = item.BranchCode , ZoneCode = @item.ZoneCode , Region = @item.Region })'">Show Details</button></td>
                                    <td style="text-align:center">@item.reqDate</td>
                                    <td style="text-align:center">@item.reqNumber</td>
                                    <td style="text-align:center">@item.TypeName</td>
                                    <td style="text-align:center">@item.TotalItems</td>
                                    <td style="text-align:center">@item.itemDescription.ToString().Substring(0, (item.itemDescription.Length > 16) ? 16 : item.itemDescription.Length)</td>
                                    <td style="text-align:center">@item.BranchName</td>
                                    <td style="text-align:center">@item.reqCreator</td>
                                    <td style="text-align:center">
                                            @item.Region
                                            <span id="bcode" style="display:none;">@item.BranchCode</span>
                                    </td>
                                </tr>
                            }
                        }
                    }
                </tbody>
            </table>
        }
    }
</div>
@section tableCss{
    <link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/datetime/1.2.0/css/dataTables.dateTime.min.css" rel="stylesheet" />
}

@section scripts{

    <script type="text/javascript" src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.2/moment.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/datetime/1.3.0/js/dataTables.dateTime.min.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/plug-ins/1.13.3/sorting/datetime-moment.js"></script>

    @Scripts.Render("~/bundles/openrequestlibraries")

    @Scripts.Render("~/bundles/openrequests")
    <script>
        $('.chkBox').each(function () {
            this.checked = false;
        });

        var clssCount = $('.chkBox').length;
        $(document).ready(function () {
            $(".checkAll").click(function () {
                $('.chkBox:checkbox').not(this).prop('checked', this.checked);
            });
        });

        //$('#BMorOthers tr').click(function () {
        //    var reqno = $(this).closest("tr").find('td:eq(1)').text();
        //    var region = $(this).closest("tr").find('#region').text();
        //    var bcode = $(this).closest("tr").find('#bcode').text();
        //    var zonecode = $(this).closest("tr").find('#zonecode').text();
        //    window.location.href = Url + '/request-details?ReqNo=' + reqno + '&BranchCode=' + bcode + '&ZoneCode=' + zonecode + '&Region=' + region;
        //    // Sample URL
        // http://localhost:61746/request-details?ReqNo=OR-HO-01P-0918-00019&BranchCode=001&ZoneCode=VISMIN&Region=PRESIDENT%20OFFICE&retUrl=head-office-open-requests
        //});

    </script>
}