DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Controllers/CloseRequestController.cs
using MySql.Data.MySqlClient;
using Newtonsoft.Json;
using OnlineRequestSystem.Models;
using OnlineRequestSystem.Service;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Globalization;
using System.Web.Mvc;

namespace OnlineRequestSystem.Controllers
{
    public class CloseRequestController : Controller
    {

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(CloseRequestController));
        private string format = "yyyy/MM/dd HH:mm:ss";
        private OpenRequestController open = new OpenRequestController();
        private Helper que = new Helper();
        private DateTime syscreated = DateTime.Now;
        private DateTime sysmodified = DateTime.Now;

        public ActionResult closeRequest(string ReqNo, string Remarks, string ReceivedDate)
        {
            var mySession = (ORSession)Session["UserSession"];
            if (mySession == null)
                return RedirectToAction("Logout", "Userlogin");

            try
            {
                var mod = new CloseRequest();
                ORtoMySql db = new ORtoMySql();
                using (var conn = db.getConnection())
                {
                    conn.Open();
                    using (var cmd = conn.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM OnlineRequest.onlineRequest_Open WHERE reqNumber = @reqNo";
                        cmd.Parameters.AddWithValue("@reqNo", ReqNo);
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.CloseConnection))
                        {
                            rdr.Read();
                            mod.reqNumber = rdr["reqNumber"].ToString().Trim();
                            mod.reqDate = rdr["reqDate"].ToString().Trim();
                            mod.reqCreator = rdr["reqCreator"].ToString().Trim();
                            mod.TypeID = rdr["TypeID"].ToString().Trim();
                            mod.reqDescription = rdr["reqDescription"].ToString().Trim();
                            mod.BranchCode = rdr["BranchCode"].ToString().Trim();
                            mod.Area = rdr["Area"].ToString().Trim();
                            mod.AreaCode = rdr["AreaCode"].ToString().Trim();
                            mod.Region = rdr["Region"].ToString().Trim();
                            mod.DivCode = rdr["DivCode"].ToString().Trim();
                            mod.DeptCode = rdr["DeptCode"].ToString().Trim();
                            mod.ZoneCode = rdr["Zonecode"].ToString().Trim();
                            mod.reqStatus = rdr["reqStatus"].ToString().Trim();
                            mod.isApproved = rdr["isApproved"].ToString().Trim();
                            mod.isDivRequest = Convert.ToInt32(rdr["isDivRequest"]);
                            mod.forPresident = Convert.ToInt32(rdr["forPresident"]);
                        }

                        if (InsertCloseTable(mod, Remarks, ReceivedDate) == "success")
                        {
                            cmd.CommandText = "DELETE FROM OnlineRequest.onlineRequest_Open WHERE reqNumber = @reqNo ";
                            cmd.Parameters.Clear();
                            cmd.Parameters.AddWithValue("@reqNo", ReqNo);
                            conn.Open();
                            if (cmd.ExecuteNonQuery() == 1)
                            {
                                log.Info("A request has been closed by: " + mySession.s_fullname + " || request no: " + ReqNo);
                                que.SetDateModified(ReqNo, mySession.s_usr_id);
                                return Json(new { status = true, rescode = "2000", msg = "Request Successfully Closed." }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        else
                        {
                            log.Error("Database Connection Error");
                            return Json(new { status = false, rescode = "2000", msg = "Database Connection Error" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
            }
            catch (Exception x)
            {
                log.Fatal(x.Message, x);
                return Json(new { status = false, rescode = "2000", msg = "Error." }, JsonRequestBehavior.AllowGet);
            }
            return RedirectToAction("ViewOpenRequest", "OpenRequest");
        }

        public ActionResult closeRequestDetails(string Region, string ZoneCode, string ReqNo, string BranchCode, CloseRequest model)
        {
            ViewBag.ReqNo = ReqNo;

            var mySession = (ORSession)Session["UserSession"];
            if (mySession == null) return RedirectToAction("Logout", "Userlogin");

            try
            {
                var itemLists = new List<RequestItems>();
                var db = new ORtoMySql();
                using (var con = db.getConnection())
                {
                    con.Open();
                    using (var cmd = con.CreateCommand())
                    {
                        cmd.CommandText = "SELECT * FROM OnlineRequest.onlineRequest_Close WHERE reqNumber = @ReqNo1";
                        cmd.Parameters.AddWithValue("@ReqNo1", ReqNo);
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.CloseConnection))
                        {
                            string TypeName = "";
                            if (rdr.HasRows)
                            {
                                rdr.Read();
                                model.reqNumber = rdr["reqNumber"].ToString().Trim();
                                model.reqDate = rdr["reqDate"].ToString().Trim();
                                model.reqCreator = rdr["reqCreator"].ToString().Trim();
                                TypeName = rdr["TypeID"].ToString().Trim();
                                ViewBag.requestName = getRequestType(TypeName);
                                model.TypeID = rdr["TypeID"].ToString().Trim();
                                model.reqDescription = rdr["reqDescription"].ToString().Trim();
                                model.BranchCode = rdr["BranchCode"].ToString().Trim();
                                model.DivCode = rdr["DivCode"].ToString().Trim();
                                model.DeptCode = rdr["DeptCode"].ToString().Trim();
                                model.Region = rdr["Region"].ToString().Trim();
                                model.Area = rdr["Area"].ToString().Trim();
                                model.AreaCode = rdr["AreaCode"].ToString().Trim();
                                model.ZoneCode = rdr["ZoneCode"].ToString().Trim();
                                model.reqStatus = rdr["reqStatus"].ToString().Trim();
                                model.isDivRequest = Convert.ToInt32(rdr["isDivRequest"]);
                                model.ClosedDate = rdr["ClosedDate"].ToString().Trim();
                                model.ClosedBy = rdr["ClosedBy"].ToString().Trim();
                                model.BranchName = open.GetRequestDetails_DivOrBranchName(model.isDivRequest, model.BranchCode, Region, ZoneCode, model.DeptCode);
                                if (model.reqStatus != "DISAPPROVED")
                                {
                                    model.ReceivedDate = Convert.ToDateTime(rdr["ReceivedDate"]);
                                }
                                model.Remarks = rdr["Remarks"].ToString().Trim();
                                model.forPresident = Convert.ToInt32(rdr["forPresident"]);
                            }
                        }
                        cmd.CommandText = "SELECT * FROM OnlineRequest.requestItems WHERE reqNumber = @ReqNo2";
                        cmd.Parameters.AddWithValue("@ReqNo2", ReqNo);
                        con.Open();
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.CloseConnection))
                        {
                            while (rdr.Read())
                            {
                                var i = new RequestItems();
                                i.ItemDescription = rdr["itemDescription"].ToString().Trim();
                                i.ItemQty = rdr["qty"].ToString().Trim();
                                i.ItemUnit = rdr["unit"].ToString().Trim();
                                i.ItemStatus = rdr["itemStatus"].ToString().Trim();
                                i.isCheckedSDC = Convert.ToInt32(rdr["isCheckedSDC"].ToString().Trim());

                                i.actualQtySDC = rdr["actualQtySDC"].ToString().Trim();
                                if (string.IsNullOrEmpty(i.actualQtySDC))
                                {
                                    i.actualQtySDC = "0";
                                }

                                i.isCheckedMMD = Convert.ToInt32(rdr["isCheckedMMD"].ToString().Trim());
                                i.actualQtyMMD = rdr["actualQtyMMD"].ToString().Trim();
                                if (string.IsNullOrEmpty(i.actualQtyMMD))
                                {
                                    i.actualQtyMMD = "0";
                                }

                                i.isCheckedBranch = Convert.ToInt32(rdr["isCheckedBranch"].ToString().Trim());
                                i.actualQtyBranch = rdr["actualQtyBranch"].ToString().Trim();
                                if (string.IsNullOrEmpty(i.actualQtyBranch))
                                {
                                    i.actualQtyBranch = "0";
                                }

                                i.isCheckedDiv = Convert.ToInt32(rdr["isCheckedDiv"].ToString().Trim());
                                i.actualQtyDiv = rdr["actualQtyDiv"].ToString();

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Views/CloseRequest/ViewCloseRequest.cshtml
@model OnlineRequestSystem.Models.CloseReqInfo
@{
    ViewBag.Title = "ViewCloseRequest";
}
<br />
<div class="jumbotron boxShadow col-md-12" style="width: 1300px; margin-left: -4.5%; padding-right: 0px; padding-left: 0px">
    <div class="panel-heading" style="background-color:#1b5fdc;color:white;">
        <b class="orHeader"><span>@ViewBag.c REQUESTS</span>&nbsp;</b>
    </div>
    <div>
        <div style="padding-top:7px;"></div>
        <table class="table-hover table_data" id="CloseTable" cellspacing="0">
            <thead>
                <tr>
                    <th style="text-align:center">Select</th>
                    <th class="col-sm-1" style="text-align:center">Date Closed</th>
                    <th class="col-sm-2" style="text-align:center">Request no.</th>
                    <th class="col-sm-2" style="text-align:center">Type</th>
                    <th class="col-sm-1" style="text-align:center">Count</th>
                    <th class="col-sm-2" style="text-align:center">Description</th>
                    <th class="col-sm-2" style="text-align:center">Branch/Division</th>
                    <th class="col-sm-2" style="text-align:center">Author</th>
                    <th class="col-sm-2" style="text-align:center">Region</th>
                </tr>
            </thead>
            <tbody style="font-size:12px;">
                @foreach (var item in Model._CloseInfo)
                {
                    <tr class="cellspacer">
                        <td style="text-align:center"><button class="btn btn-sm btn-primary" onclick="location.href='@Url.Action("closeRequestDetails", "CloseRequest", new { ReqNo = item.reqNumber, BranchCode = item.BranchCode, ZoneCode = @item.ZoneCode, Region = @item.Region })'">Show Details</button></td>
                        <td style="text-align:center" data-sort='@item.sortreqDate'>@item.closedDate</td>
                        <td style="text-align:center"> @item.reqNumber</td>
                        <td style="text-align:center">@item.TypeName</td>
                        <td style="text-align:center">@item.TotalCount</td>
                        <td style="text-align:center">@item.itemDescription</td>
                        <td style="text-align:center">@item.BranchName</td>
                        <td style="text-align:center">@item.reqCreator</td>
                        <td style="text-align:center">
                            @item.Region
                            <span style="display:none;">@item.BranchCode</span>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section tableCss{
    <link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

@section scripts{
    <script src="~/Scripts/table/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/table/dataTables.min.js"></script>
    <script>
        $('#CloseTable').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });

        $(".table_link").on("click", function () {
            $('#CloseTable').DataTable().state.clear();
        });
    </script>
}

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Views/CloseRequest/closeRequestDetails.cshtml
@model OnlineRequestSystem.Models.CloseRequest
@{
    ViewBag.Title = "RequestDetails";
    var mySession = (OnlineRequestSystem.Models.ORSession)Session["UserSession"];
    DateTime DateRecieved = Convert.ToDateTime(Model.ReceivedDate);

    string dis = "";
    dis = "disabled";

    string BranchOrDivisionName = "";
    if (Model.isDivRequest == 1)
    { BranchOrDivisionName = "Division Name :"; }
    else
    { BranchOrDivisionName = "Branch Name :"; }
}
<br />

<div class="jumbotron col-md-12 boxShadow" style="padding-right: 0px; padding-left: 0px">
    <div class="panel-heading" style="background-color:#1b5fdc;color:white;">
        <div class="pull-left orHeader">
            Requested by:&nbsp;<b>@Model.reqCreator</b>
        </div>
        <div class="text-right orHeader">
            <b>@Model.reqNumber </b>
            @Html.TextBoxFor(m => m.reqNumber, new { @value = Model.reqNumber, @id = "Req", @style = "display:none;" })
        </div>
    </div>
    <center>
        <h2 style="color:red;position:initial"><b>REQUEST @Model.reqStatus</b></h2>
    </center>
    <br />
    <div class="container">
        <div class="container">
            <div class="col-md-6">
                <label>Request Description:</label>
                @Html.TextArea("Description", Model.reqDescription, new { @readonly = "readonly", @class = "form-control", @rows = "3", @style = "resize:none;max-width:inherit;", @required = "required" })
            </div>
            <div class="col-md-3">
                <label>@BranchOrDivisionName</label>
                @Html.DisplayFor(m => m.BranchName, new { @class = "form-control" })
                <div style="display:none" id="officeName">@Model.BranchName</div>
                <br />
                <label>Branch Code : </label>
                @Html.DisplayFor(m => m.BranchCode, new { @class = "form-control" })
                <br />
                <label>Date Requested : </label>
                @Model.reqDate
                <br />
                <label>Status : </label>
                @Model.reqStatus
            </div>
            <div class="col-md-3">
                <label>Region : </label>
                @Html.DisplayFor(m => m.Region, new { @class = "form-control" })
                <div style="display:none" id="RegionNamee">@Model.Region</div>
                <br />
                @if (@Model.isDivRequest == 0)
                {
                    <label>Area : </label>
                    @Html.DisplayFor(m => m.Area, new { @class = "form-control" })
                    <br />
                }
                <label>Zone Code : </label>
                @Html.DisplayFor(m => m.ZoneCode, new { @class = "form-control" })
                <br />
                <label>Request type : </label>
                <div id="RequestTypeName">@ViewBag.requestName</div>
                @Html.TextBoxFor(m => m.TypeID, new { @style = "display:none;" })
            </div>
        </div>
    </div>
    <br />

    <div class="col-md-12">
        <table class="table table-bordered table-hover table-condensed" id="myTable">
            <thead>
                <tr style="background-color:#1b5fdc;color:white;" class="orHeader">
                    <th class="col-md-4"><center>Item Name</center></th>
                    <th class="col-md-1"><center>Item Quantity</center></th>
                    <th class="col-md-1"><center>MMD</center></th>
                    @if (Model.isDivRequest == 0)
                    {
                        <th class="col-md-1"><center>SDC</center></th>
                        <th class="col-md-1"><center>Branch</center></th>
                    }
                    else
                    {
                        <th class="col-md-1"><center>Division</center></th>
                    }
                    <th class="col-md-1"><center>Status</center></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ReqItems)
                {
                    <tr>
                        <td id="itemDesc" style="overflow: auto; vertical-align:middle; max-width:100px">
                            @item.ItemDescription
                        </td>
                        <td id="itemQty">
                            <center> @item.ItemQty&nbsp;&nbsp;<i>@item.ItemUnit</i></center>
                        </td>
                        <td style="padding:1px; vertical-align: middle">
                            <center>
                                @if (item.isCheckedMMD == 1)
                                {
                                    <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkMMD" value="1" style="vertical-align: middle; margin: -4px 0 0 0" checked />
                                }
                                else
                                {
                                    <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkMMD" style="vertical-align: middle; margin: -4px 0 0 0" value="1" />
                                }
                                <input type="text" class="ReqDetailsBlock" id="txtMMD" disabled value="@item.actualQtyMMD" maxlength="6" />
                                <i class="@item.MMDstatus itmstatus" style="font-size:16px"></i>
                            </center>
                        </td>
                        @if (Model.isDivRequest == 0)
                        {
                            <td style="padding:1px; vertical-align: middle">
                                <center>
                                    @if (item.isCheckedSDC == 1)
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkSDC" value="1" style="vertical-align: middle; margin: -4px 0 0 0" checked />
                                    }
                                    else
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkSDC" value="1" style="vertical-align: middle; margin: -4px 0 0 0" />
                                    }
                                    <input type="text" class="ReqDetailsBlock" id="txtSDC" disabled maxlength="6" value=@item.actualQtySDC />
                                    <i class="@item.SDCStatus itmstatus" style="font-size:16px"></i>
                                </center>
                            </td>

                            <td style="padding:1px; vertical-align: middle">
                                <center>
                                    @if (item.isCheckedBranch == 1)
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkBranch" value="1" style="vertical-align: middle; margin: -4px 0 0 0" checked />
                                    }
                                    else
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkBranch" value="1" style="vertical-align: middle; margin: -4px 0 0 0" />
                                    }
                                    <input type="text" class="ReqDetailsBlock" id="txtBranch" disabled maxlength="6" value=@item.actualQtyBranch />

                                    <i class="@item.BranchStatus itmstatus" style="font-size:16px"></i>
                                </center>
                            </td>
                        }
                        else
                        {
                            <td style="padding:1px; vertical-align: middle">
                                <center>
                                    @if (item.isCheckedDiv == 1)
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkDiv" name="ReqDetailsCheckbox4" value="1" style="vertical-align: middle; margin: -4px 0 0 0" checked />
                                    }
                                    else
                                    {
                                        <input type="checkbox" @dis class="ReqDetailsCheckbox" id="chkDiv" name="ReqDetailsCheckbox4" value="1" style="vertical-align: middle; margin: -4px 0 0 0" />
                                    }
                                    <input type="text" class="ReqDetailsBlock" id="txtDiv" disabled maxlength="6" value=@item.actualQtyDiv />
                                    <i class="@item.DivStatus itmstatus" style="font-size:16px"></i>
                                </center>
                            </td>

                        }
                        <td class="status" style="text-align:center">@item.ItemStatus</td>
                    </tr>
                }
            </tbody>
        </table>

        <input id="isRequest" value="Close" hidden />

        <hr style="border-bottom:1px solid #808080" />

        @if (Model.reqStatus == "CLOSED")
        {
            <div class="col-md-12">
                <div class="col-md-6">
                    <span><b>Closed by: </b>@Model.ClosedBy</span>
                    <br />
                    <span><b>Date Received: </b>@DateRecieved.ToShortDateString()</span>
                    @Html.TextAreaFor(m => m.Remarks, new { @class = "form-control", @rows = "3", @style = "resize:none;max-width:inherit;", @readonly = "readonly", @title = "Testing ra" })
                    <hr style="border-bottom:1px solid #808080" />
                </div>
            </div>
        }

        @if (Model.isDivRequest == 1)
        {
            { Html.RenderPartial("DetailsPartials/_DMApproval"); }
            { Html.RenderPartial("DetailsPartials/_LocalDIV"); }
        }

        @if (!(new[] { "001", "002" }).Contains(Model.BranchCode))
        {
            { Html.RenderPartial("DetailsPartials/_AMApproval"); }
            { Html.RenderPartial("DetailsPartials/_RMApproval"); }
        }
        @if (Model.isDivRequest == 0)
        {
            { Html.RenderPartial("DetailsPartials/_VPAssistant"); }
            { Html.RenderPartial("DetailsPartials/_GMApproval"); }
        }
        @{Html.RenderPartial("DetailsPartials/_DivApproval");}
        @{Html.RenderPartial("DetailsPartials/_DivApproval2");}
        @{Html.RenderPartial("DetailsPartials/_DivApproval3");}

        @{Html.RenderPartial("DetailsPartials/_PresApproval");}
        @{Html.RenderPartial("DetailsPartials/_VPO_POApproval");}
        @{Html.RenderPartial("DetailsPartials/_Pres_POApproval");}
        @{Html.RenderPartial("DetailsPartials/_MMDProcesses");}
    </div>
</div>