DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Controllers/PendingController.cs
using MySql.Data.MySqlClient;
using OnlineRequestSystem.Models;
using OnlineRequestSystem.Service;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;

namespace OnlineRequestSystem.Controllers
{
    public class PendingController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(PendingController));
        private PendingQueries que = new PendingQueries();
        private OpenRequestController oReq = new OpenRequestController();
        private Helper help = new Helper();

        [Route("pending-requests")]
        public ActionResult PendingRequests(OpenReqInfo Info)
        {
            var ss = (ORSession)Session["UserSession"];
            if (ss == null) return RedirectToAction("Logout", "Userlogin");
            
            try
            {
                var toTC = new CultureInfo("en-US", false).TextInfo;
                var db = new ORtoMySql();
                using (var conn = db.getConnection())
                {
                    var OpenReqList = new List<OpenReqViewModel>();
                    using (var cmd = conn.CreateCommand())
                    {
                        if (ss.s_costcenter == "0001MMD")
                        {
                            que.Pending_MMD_Vismin(ss, Info);
                            return View(Info);
                        }
                        if (ss.s_costcenter == "0002MMD")
                        {
                            que.Pending_MMD_Luzon(ss, Info);
                            return View(Info);
                        }
                        if (ss.s_job_title == "AREA MANAGER")
                        {
                            que.Pending_AM(ss, Info);
                            return View(Info);
                        }
                        else if (ss.s_job_title == "REGIONAL MAN")
                        {
                            que.Pending_RM(ss, Info);
                            return View(Info);
                        }
                        else if (ss.s_isDepartmentApprover == 1)
                        {
                            que.Pending_Dept_Approver(ss, Info);
                            return View(Info);
                        }
                        else if (ss.s_isDivisionApprover == 1 && ss.s_task != "GMO-GENMAN" && ss.s_usr_id != "LHUI1011873")
                        {
                            que.Pending_Div_Approver(ss, Info);
                            return View(Info);
                        }
                        else if (ss.s_task == "GMO-GENMAN" || ss.s_isVPAssistant == 1)
                        {
                            que.Pending_GMO(ss, Info);
                            return View(Info);
                        }
                        else if (ss.s_usr_id == "LHUI1011873")
                        {
                            que.Pending_President(ss, Info);
                            return View(Info);
                        }
                        else
                        {
                            cmd.CommandText = " SELECT " +
                                              " a.reqNumber,  a.reqCreator, a.reqDescription, COUNT(d.itemDescription) AS TotalCount, a.reqDate, a.TypeID , a.reqTotal, a.BranchCode, a.Region, a.DivCode, " +
                                              " ( SELECT itemDescription FROM requestItems WHERE reqnumber = a.reqnumber ORDER BY itemDescription ASC LIMIT 1  ) AS Description, " +
                                              " a.Zonecode, a.reqStatus, a.isDivRequest,b.isApprovedLocalDiv, a.DeptCode, a.forPresident," +
                                              " b.isApprovedDM, c.isDMApproval, " +
                                              " b.isApprovedAM, c.isAMApproval, " +
                                              " b.isApprovedRM ,c.isRMApproval, " +
                                              " b.isApprovedGM, c.isGMApproval, b.isApprovedVPAssistant," +
                                              " b.isApprovedDiv1, c.isDivManApproval, " +
                                              " b.isApprovedDiv2, c.isDivManApproval2, " +
                                              " b.isApprovedDiv3, c.isDivManApproval3, " +
                                              " b.isApprovedPres, c.isPresidentApproval, " +
                                              " b.isMMDProcessed, b.isDelivered, b.isMMDTransit, c.DivCode1, c.DivCode2, c.DivCode3 " +
                                              " FROM onlineRequest_Open a " +
                                              " INNER JOIN requestApproverStatus b ON a.reqNumber = b.reqNumber " +
                                              " INNER JOIN requestType c ON a.TypeID = c.TypeID " +
                                              " INNER JOIN requestItems d ON d.reqNumber = a.reqNumber  " +
                                              " WHERE a.reqStatus = 'PENDING' AND (a.BranchCode = @BranchCode AND a.Region = @Region AND a.ZoneCode = @ZoneCode) " +
                                              " AND a.reqCreator = @Creator GROUP BY a.reqNumber ORDER BY a.syscreated ASC ";
                            cmd.Parameters.AddWithValue("@Region", ss.s_region);
                            cmd.Parameters.AddWithValue("@Creator", ss.s_fullname);
                            cmd.Parameters.AddWithValue("@BranchCode", ss.s_comp);
                            cmd.Parameters.AddWithValue("@ZoneCode", ss.s_zonecode);
                        }

                        conn.Open();
                        using (var rdr = cmd.ExecuteReader(CommandBehavior.CloseConnection))
                        {
                            while (rdr.Read())
                            {
                                var o = new OpenReqViewModel();
                                o.reqNumber = rdr["reqNumber"].ToString().Trim();
                                o.reqCreator = toTC.ToTitleCase(rdr["reqCreator"].ToString().Trim().ToLower());
                                o.itemDescription = rdr["Description"].ToString().Trim();
                                o.reqDescription = rdr["reqDescription"].ToString().Trim();
                                //o.reqDate = string.Format("{0:MM/dd/yyyy}", Convert.ToDateTime(rdr["reqDate"].ToString()));
                                var dt = Convert.ToDateTime(rdr["reqDate"].ToString());
                                var day = (dt.Day < 10) ? "0" + dt.Day.ToString() : dt.Day.ToString();
                                var month = (dt.Month < 10) ? "0" + dt.Month.ToString() : dt.Month.ToString();
                                var year = dt.Year.ToString();
                                o.sortreqDate = year + month + day;
                                o.reqDate = month + "/" + day + "/" + year;
                                o.TypeID = rdr["TypeID"].ToString().Trim();
                                o.TypeName = help.GetTypeName(o.TypeID);
                                o.TotalItems = rdr["TotalCount"].ToString().Trim();
                                o.BranchCode = rdr["BranchCode"].ToString().Trim();
                                o.ZoneCode = rdr["Zonecode"].ToString().Trim();
                                o.isDivRequest = rdr["isDivRequest"].ToString().Trim();
                                o.DeptCode = rdr["DeptCode"].ToString().Trim();
                                o.Region = rdr["Region"].ToString().Trim().ToUpper();
                                if (o.Region == "HO")
                                {
                                    o.Region = oReq.GetOR_DivisionName(o.DeptCode).ToUpper();
                                }
                                o.forPresident = rdr["forPresident"].ToString().Trim();
                                if (o.isDivRequest == "1")
                                {
                                    o.BranchName = oReq.getBranchname(o.BranchCode, "HO", o.ZoneCode);
                                }
                                else
                                {
                                    o.BranchName = toTC.ToTitleCase(oReq.getBranchname(o.BranchCode, o.Region, o.ZoneCode).ToLower()).Replace("Ml ", "ML ");
                                }

                                if (!(new[] { "001", "002" }).Contains(o.BranchCode))
                                {
                                    o.isApprovedAM = Convert.ToInt32(rdr["isApprovedAM"]);
                                    o.isApprovedRM = Convert.ToInt32(rdr["isApprovedRM"]);
                                    o.reqAM = Convert.ToInt32(rdr["isAMApproval"]);
                                    o.reqRM = Convert.ToInt32(rdr["isRMApproval"]);
                                }
                                o.isApprovedLocalDiv = Convert.ToInt32(rdr["isApprovedLocalDiv"]);
                                o.isApprovedDM = Convert.ToInt32(rdr["isApprovedDM"]);
                                o.isApprovedGM = Convert.ToInt32(rdr["isApprovedGM"]);
                                o.isApprovedVPAssistant = Convert.ToInt32(rdr["isApprovedVPAssistant"]);
                                o.isApprovedDiv1 = Convert.ToInt32(rdr["isApprovedDiv1"]);
                                o.isApprovedDiv2 = Convert.ToInt32(rdr["isApprovedDiv2"]);
                                o.isApprovedDiv3 = Convert.ToInt32(rdr["isApprovedDiv3"]);
                                o.isApprovedPres = Convert.ToInt32(rdr["isApprovedPres"]);

                                o.DivCode1 = rdr["DivCode1"].ToString().Trim();
                                o.DivCode2 = rdr["DivCode2"].ToString().Trim();
                                o.DivCode3 = rdr["DivCode3"].ToString().Trim();
                                o.reqDM = Convert.ToInt32(rdr["isDMApproval"]);

DEV/Online Request v3.5/OnlineRequestSystem/OnlineRequestSystem/Views/Pending/PendingRequests.cshtml
@model OnlineRequestSystem.Models.OpenReqInfo
@{
    ViewBag.Title = "View Pending Requests";
    var mySession = (OnlineRequestSystem.Models.ORSession)Session["UserSession"];

}
<br />
<div class="jumbotron boxShadow col-md-12" style="width: 1300px; margin-left: -4.5%; padding-right: 0px; padding-left: 0px">
    <div class="panel-heading" style="background-color:#ff5722;color:white;">
        <b class="orHeader">PENDING REQUESTS</b>
    </div>

    <div style="padding-top:7px;"></div>
    @if ((new[] { "0001MMD", "0002MMD" }).Contains(mySession.s_costcenter) || mySession.s_job_title == "MMD-DIVMAN")
    {
        @Html.Partial("PendingReqPartials/_Pending_MMD", Model);
    }
    else
    {
        if (mySession.s_isDepartmentApprover == 1)
        {
            @Html.Partial("PendingReqPartials/_Pending_DM", Model);
        }
        if (mySession.s_job_title == "AREA MANAGER")
        {
            @Html.Partial("PendingReqPartials/_Pending_AM", Model);
        }
        else if (mySession.s_job_title == "REGIONAL MAN")
        {
            @Html.Partial("PendingReqPartials/_Pending_RM", Model);
        }
        else if (mySession.s_isDivisionApprover == 1 && mySession.s_task != "GMO-GENMAN" && mySession.s_usr_id != "LHUI1011873")
        {
            @Html.Partial("PendingReqPartials/_Pending_Div", Model);
        }
        else if (mySession.s_job_title == "GMO-GENMAN")
        {
            @Html.Partial("PendingReqPartials/_Pending_GM", Model);
        }
        else if (mySession.s_usr_id == "LHUI1011873")
        {
            @Html.Partial("PendingReqPartials/_Pending_Pres", Model);
        }
        else
        {
            if (mySession.s_isDepartmentApprover != 1)
            {
                <div style="padding-top:7px;"></div>
                <table class="table-hover" id="BMorOthers">
                    <thead>
                        <tr>
                            <th style="text-align:center">Select</th>
                            <th class="col-sm-1" style="text-align:center">Date</th>
                            <th class="col-sm-2" style="text-align:center">Request no.</th>
                            <th class="col-sm-2" style="text-align:center">Types</th>
                            <th class="col-sm-1" style="text-align:center">Count</th>
                            <th class="col-sm-2" style="text-align:center">Description</th>
                            <th class="col-sm-2" style="text-align:center">Branch/Division</th>
                            <th class="col-sm-2" style="text-align:center">Author</th>
                            <th class="col-sm-2" style="text-align:center">Region</th>
                        </tr>
                    </thead>
                    <tbody style="font-size:12px;">
                        @if (Model._OpenInfo != null)
                        {
                            foreach (var item in Model._OpenInfo)
                            {
                                if (item.reqCreator == mySession.s_fullname)
                                {
                                    <tr class="cellspacer">
                                        <td style="text-align:center"><button class="btn btn-sm btn-warning" style="border-color:#bf360c85;background-color:#ff5722" onclick="location.href='@Url.Action("PendingDetails", "Pending", new { ReqNo = item.reqNumber, BranchCode = item.BranchCode, ZoneCode = @item.ZoneCode, Region = @item.Region })'">Show Details</button></td>
                                        <td style="text-align:center" data-sort='@item.sortreqDate'>@item.reqDate</td>
                                        <td style="text-align:center">@item.reqNumber</td>
                                        <td style="text-align:center">@item.TypeName</td>
                                        <td style="text-align:center">@item.TotalItems</td>
                                        <td style="text-align:center">@item.itemDescription</td>
                                        <td style="text-align:center">@item.BranchName</td>
                                        <td style="text-align:center">@item.reqCreator</td>
                                        <td style="text-align:center">
                                            @item.Region
                                            <span style="display:none;">@item.BranchCode</span>
                                        </td>
                                    </tr>
                                }
                            }
                        }
                    </tbody>
                </table>
            }
        }
    }
</div>

@section tableCss{
    <link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
}

@section scripts{

    @Scripts.Render("~/bundles/openrequestlibraries")
  
    <script>
        $('#MMDOpenRequest').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#BMorOthers').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#AMOpen').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#DeptOpenReq').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#DivisionOpenReq').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#GMOpen').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#PresidentOpen').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });
        $('#RMOpen').DataTable({
            "order": [[1, "asc"]], "bSort": false, stateSave: true
        });

        $(".table_link").on("click", function () {
            $('#MMDOpenRequest,#BMorOthers,#AMOpen,#DeptOpenReq,#DivisionOpenReq,#GMOpen,#PresidentOpen,#RMOpen').DataTable().state.clear();
        });
    </script>
}